//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PICT()
        {
            this.QUIZ_PICT = new HashSet<QUIZ_PICT>();
        }
    
        public int PICT_ID { get; set; }
        public string PICT_PATH { get; set; }
        public string PICT_TITLE { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public System.DateTime EDIT_DT { get; set; }
        public int DELETE_FLG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUIZ_PICT> QUIZ_PICT { get; set; }
    }
}
