//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUIZ_PICT
    {
        public int QUIZ_ID { get; set; }
        public int HINT_SEQ { get; set; }
        public int PICT_ID { get; set; }
        public string HINT_TXT { get; set; }
        public int DELETE_FLG { get; set; }
    
        public virtual PICT PICT { get; set; }
        public virtual QUIZ QUIZ { get; set; }
    }
}
