//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUIZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUIZ()
        {
            this.ANSWER_HIST = new HashSet<ANSWER_HIST>();
            this.QUIZ_PICT = new HashSet<QUIZ_PICT>();
        }
    
        public int QUIZ_ID { get; set; }
        public string QUIZ_NAME { get; set; }
        public string QUIZ_DETAIL { get; set; }
        public int USER_ID { get; set; }
        public int CHALLENGE_NUM { get; set; }
        public int CLEAR_NUM { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string ANSWER_HIRAGANA { get; set; }
        public string ANSWER { get; set; }
        public string ANSWER_DETAIL { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public System.DateTime EDITED_DT { get; set; }
        public int DELETE_FLG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWER_HIST> ANSWER_HIST { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUIZ_PICT> QUIZ_PICT { get; set; }
    }
}
