//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideShow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SakanaDBEntities1 : DbContext
    {
        public SakanaDBEntities1()
            : base("name=SakanaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ANSWER_HIST> ANSWER_HIST { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<PICT> PICT { get; set; }
        public virtual DbSet<QUIZ_PICT> QUIZ_PICT { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<QUIZ> QUIZ { get; set; }
    }
}
